export const PROJECTS_LOADING_REQUEST: string = "PROJECTS_LOADING_REQUEST";
export const PROJECTS_LOADING_SUCCESS: string = "PROJECTS_LOADING_SUCCESS";
export const PROJECTS_LOADING_FAIL: string = "PROJECTS_LOADING_FAIL";

export const GET_TRENDING_REQUEST: string = "GET_TRENDING_REQUEST";
export const GET_TRENDING_SUCCESS: string = "GET_TRENDING_SUCCESS";
export const GET_TRENDING_FAIL: string = "GET_TRENDING_FAIL";

export const GET_RECOMMENDED_REQUEST: string = "GET_RECOMMENDED_REQUEST";
export const GET_RECOMMENDED_SUCCESS: string = "GET_RECOMMENDED_SUCCESS";
export const GET_RECOMMENDED_FAIL: string = "GET_RECOMMENDED_FAIL";

export const GET_LATEST_REQUEST: string = "GET_LATEST_REQUEST";
export const GET_LATEST_SUCCESS: string = "GET_LATEST_SUCCESS";
export const GET_LATEST_FAIL: string = "GET_LATEST_FAIL";
