export const PROJECTS_LOADING_REQUEST: string = "PROJECTS_LOADING_REQUEST";
export const PROJECTS_LOADING_SUCCESS: string = "PROJECTS_LOADING_SUCCESS";
export const PROJECTS_LOADING_FAIL: string = "PROJECTS_LOADING_FAIL";
